language: node_js
node_js:
  - lts/*
branches:
  only:
    - master    # 构建的分支
install:
  - pnpm install
script:
  - pnpm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vitepress/dist
  target-branch: gh-pages
  # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
