name: imm-ui-pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install and Build 🔧
        run: |
          pnpm install
          pnpm run docs:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist
