name: Publish docs to github actions

# 当 master 分支 push 代码的时候触发 workflows
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 下载仓库代码 / 校验
      - name: Checkout
        # actions/checkout@v3 是 github 官方的一个action，用于 clone 该仓库的源码到工作流中
        uses: actions/checkout@v3

      # 安装 node
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          # cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm

      # 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Install
        run: pnpm install
      # This step installs the ssh client into the workflows run. There's many options available for this on the action marketplace.
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        #env:
          #SSH_AUTH_SOCK: /tmp/ssh-auth.sock
      # 发布page
      - name: Build and Deploy Repo
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          SSH: true # SSH must be set to true so the deploy action knows which protocol to deploy with.

